# Generated by Django 4.1.6 on 2024-01-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_remove_profile_id_alter_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='author_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
