# Generated by Django 4.1.6 on 2024-01-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
