# Generated by Django 4.1.6 on 2024-01-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='author_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
